### ISSUE TITLE
Add last-seen time to trolley

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-api-dot-net#15]
Record last beacon time for each trolley for debug purposes.   Return only with the detailed trolley record, not in the "Active Running" API call.

**Comment by ajhodges** [comment]
:+1: :)

**Comment by bikeoid** [comment]
Currently deployed to Dev instance at http://yeahthattrolley.azurewebsites.net/Trolleys , should be deployed to production server in the next day or so.

**Comment by Linktheoriginal** [comment]
Currently pulling this information in the web app.  The popup disappears when the trolley moves, however.
