### ISSUE TITLE
Authentication for Web API

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-api-dot-net#2]
Microsoft doesn't support Basic Authentication out of the box, so it was manually added in the App_Start folder.   The passwords were embedded in the software.   What is the proper way to assign basic auth credentials so that they don't appear in the public Repo?    Is there a better way to authenticate our web app?

**Comment by thedanfields** [comment]
We should plop them in the backing datastore on the user table or something
like it.

**Comment by bikeoid** [comment]
That's a good idea - adding roles to that table will also solve both authorization issues at once.

**Comment by bikeoid** [comment]
Added roles and rely on unpublished datastore in #2
