### ISSUE TITLE
Add Vector route editor

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-api-dot-net#22]
There are frequent route deviations when one or more blocks are closed for an event.    It is useful to have the capability to create derived routes based on standard routes, and schedule them for the duration of the event.   The ideal solution is a Javascript-based vector editor to allow the client to edit route travel paths directly and easily.     Should minimize mouse clicks and edit time to modify a route.

  * Need to indicate direction of travel.
  * Should snap to intersections for ease and quickness of use
   * Indicate bidirectional travel and allow edits on either direction.
   * Check for continuous circular loop before final save
    * Support for "temporary route" which automatically expires after a period of time if not referenced by a schedule to prevent endless buildup of similar route names that cannot be re-used or relocated.    Alternatively create a method of indexing to allow a large number of routes to be stored and reused.

**Comment by bikeoid** [comment]
A doodle at http://yeahthattrolley.azurewebsites.net/Routes/RouteShape/1 (no login required to view).   It's still very preliminary, but the route path is shown along with a blue dot at each intersection.     There is no vector edit capability yet.  The end result may not look anything like this.

**Comment by alexdresko** [comment]
Can't TT just defer the route based on where the driver actually travels rather than pre-designing and scheduling routes?

**Comment by bikeoid** [comment]
Yes, that would be possible, but the tradeoff is a loss of features that benefit riders.

  * There have been up to 5 route changes in a single day, could be more in the future
  * The first route of each day or after each schedule change would be lost or incorrect (showing the previous schedule).
   * Riders would not be able to plan by viewing a future schedule, then be able to click to see where the route goes.
   * Inability to screen out the path a trolley takes between the "garage" or maintenance/break to the route.   Not a big issue today, but could be more important after the new routes are added.

  The days of "2 fixed routes that will never change" have long gone.

**Comment by bikeoid** [comment]
Greenlink can now produce .KML files that match our needs: a full circle that matches the route path.   All that is needed is to implement a proper KML upload with error checking / reporting and visual confirmation before applying to the route.
