### ISSUE TITLE
Snap to Roads on the Route Map

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-api-dot-net#24]
Hey @bikeoid! Did we ever get anywhere with Leaflet.js on snapping to roads for allowing GreenLink to update the Routes? Was brought up tonight cc @dacohenii

**Comment by bikeoid** [comment]
I hadn't had time to make significant progress this month.  If there is a hack night coming up we can discuss more.

**Comment by jeremywight** [comment]
Next week if you can make it

**Comment by bikeoid** [comment]
Issue resolved in #22
