### ISSUE TITLE
WebAPI Default to JSON

### ISSUE THREAD

**Issue by bikeoid** [codeforgreenville/trolley-tracker-api-dot-net#26]
Make WebAPI return JSON by default when viewed in a browser since this is supported by most tools.  Will still support XML with explicit text/xml request

**Comment by jeremywight** [comment]
Great idea 👍

**Comment by bikeoid** [comment]
This has now been published on the real server http://api.yeahthattrolley.com/api/v1/Stops/Regular

**Comment by jeremywight** [comment]
Awesome work Mike!!!
