### ISSUE TITLE
Tasks to complete the MVP of Route Calculations

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-api-dot-net#37]
Tasks to complete the MVP of Route Calculations as discussed at the Meetup:
The goal is to create a basic MVP of giving a user the ability to have an estimation of how long it will be for a trolley to get to their selected stop on a given route. There are obviously more improvements which could be made, but this is the basic MVP implementation to give a user some insight into timing.

The completion of these tasks would allow the client apps to be provided the timing on a given route, and then they would be responsible for determining what the route is that the client needs the data for and when to make the request to the server to get this data. Again, going for the MVP here :) 

Assumptions:
We are working under the assumption that in the near future we're going to have a defined route, given by the trolley operator upon start, which we will pull an ID for.

Tasks:
() Match the trolley route based on id and assigned to a color (that's already defined [here](http://yeahthattrolley.azurewebsites.net/Routes)
() Determine the location of the trolley and it's direction of travel
() Match the location of the trolley on the route path
() Determine the timing between stops for all stops in a single loop (partially completed in this [file](https://github.com/codeforgreenville/trolley-tracker-api-dot-net/blob/1744118777e7860f0e56d9c0e205fe1a7972b006/TrolleyTracker/Models/StopArrivalTime.cs)
() Return that list of stop id's with the route id and the calculated time of arrival to each stop on that route loop

**Comment by bikeoid** [comment]
I should be able to complete the polled version of this soon - it touches several parts of the app and database.    Then anyone interested can add the Web Sockets version before we roll it out.

P.S.  The simulator will be down until the new year.

**Comment by bikeoid** [comment]
Now running on dev server at http://yeahthattrolley.azurewebsites.net/DBVisualizer?ActiveFilter=1 , click on stop to view arrival time

No automatic trolley color change if trolleys run routes other than customary - this may be obtained in the future by querying the new transit management system when the drivers log into a route.

**Comment by bikeoid** [comment]
P.S. on the dev server, the simulation zips along areas where there are no stops so that the route completes faster without excessive polling.
