### ISSUE TITLE
Possible upcoming route changes

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-api-dot-net#50]
Just an FYI

https://www.google.com/amp/s/amp.greenvilleonline.com/amp/2524021002

**Comment by bikeoid** [comment]
Comments from GvlToday ;

“I’ve  always found the route and times to be unclear. Would love to ride it  but just never quite know when and where it is or goes.” | “I’ve  always found the route and times to be unclear. Would love to ride it  but just never quite know when and where it is or goes.” |  
“I’ve  always found the route and times to be unclear. Would love to ride it  but just never quite know when and where it is or goes.” |  
 
"After news that the downtown trolley may cut some neighborhood routes, we asked on Instagram whether our followers ride the trolley. Most of the 60+ commenters said they would love to, but aren’t sure when + where to find it. There’s a trolley tracker app available to download, but commenters said it doesn’t always show the trolley’s updated location."

   One time I was on it, the tablet was running, but the Syncromatics server wasn't updating location for one of the trolleys.

**Comment by bikeoid** [comment]
All comments from Instagram https://www.instagram.com/p/Bsg0GDEl0Al/?utm_source=GVLtoday+Master&utm_campaign=3d13284b7e-EMAIL_CAMPAIGN_2018_12_28_02_22_COPY_12&utm_medium=email&utm_term=0_e278d3ec5a-3d13284b7e-36599105&mc_cid=3d13284b7e&mc_eid=502ca77c26

**Comment by bikeoid** [comment]
Too bad no one has started up a Sigfox provider in this area.   That's exactly what our application could use - just picking up our beacon broadcasting small messages for a fraction of the cost of wireless cellular.  Someone has provided service in Charlotte, Atlanta, and Memphis.  https://www.sigfox.com   .. Maybe we could start this in the city and pay for it by selling the service to anyone?
