### ISSUE TITLE
Security Notice from Github Bootstrap.Less

### ISSUE THREAD

**Issue by allella** [codeforgreenville/trolley-tracker-api-dot-net#51]
Wanted to post an issue since I didn't see one here. Via GitHub

> Known moderate severity security vulnerability detected in Bootstrap.Less >= 3.0.0, < 3.4.1 defined in packages.config.
> --
> packages.config update suggested: Bootstrap.Less ~> 3.4.1.
>

**Comment by bikeoid** [comment]
Fixed in 8f2a4ac where I upgraded to 3.4.1 of both bootstrap and bootstrap.less , I was too lazy to create an issue.
