### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by Eonasdan** [codeforgreenville/trolley-tracker-api-dot-net#9]
I have a couple of recommendations for you.
- [ ] Move to CodeFirst: it will be easier to sure everyone is on the same page with migrations, reduce developer startup and allow for seeding test data. This should be fairly easy.
- [ ] Upgrade to Bootstrap 3
- [ ] Upgrade to LESS or SASS
  - [ ] Setup a grunt/gulp task to compile to CSS
- [ ] Use .Net Identity 2 for users and roles if you're not already
  - [ ]  It would be a good idea to make sure that all the controller has the proper authorize/role detection on them. Only one page asked me to log in
- [ ] Migrate the DB Visualizer to a view that either hides the menu or has a null layout

**Comment by jeremywight** [comment]
Good suggestions. @bikeoid some things to consider, discuss post-launch
